### ISSUE TITLE
Proposals | Confirm proposal actions

### ISSUE THREAD

**Issue by SamusElderg** [spartan-protocol/SpartanProtocol-DAppV2#494]
**Phase 1:**
- [x] Propose list BNB for bond
- [x] Vote for proposal
- [x] Unvote proposal
- [x] Vote again
- [x] Poll votes
- [x] Finalise
- [x] Propose mint 2.5M bond allocation
- [x] Vote, poll & finalise
- [x] Finish #493 

**Phase 2:**
- [x] Delist bond asset (via proposal)
- [x] Finish #495 
- [x] Flip emissions on (via proposal)
- [x] Flip emissions off (via proposal)
- [x] Perform a 'REALISE' (via proposal)
- [x] Change cooloffperiod to maybe 5mins? (via proposal)
- [x] Confirm the frontend shows an accurate cooloff period
- [x] Perform a grant (via proposal)

**Phase 2a (after next deploy):**
- [x] Complete #499 
- [x] Add BUSDp curated asset (via proposal)
- [x] Add BUSDp to the daovault
- [x] Remove BUSDp as curated asset (via proposal)
- [x] Test change daoClaim (via proposal)
- [x] Test change synthClaim (via proposal)
- [x] Complete #500

**Phase 3:**
- [x] Test 'cancel' proposal
- [x] Test different weightClasses are accurate on front end (instead of just testing 100% each time)

**Phase 4:**
- [ ] Test the contract upgrade functions

**Comment by SamusElderg** [comment]
some of this issue here: 5ad6532356556dc997648f6e4696e354e91b324a
